include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.g.dart"
    - "**.config.dart"
    - "**.navigator.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    avoid_print: false
    unawaited_futures: true
