name: impaktfull_translations_example
description: A project used to demo the impaktfull_translations package
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  impaktfull_architecture: ^0.3.1
  impaktfull_ui: ^0.13.0
  intl: ^0.19.0
  provider: ^6.0.5
  sprintf: ^7.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  impaktfull_translations:
    path: ../

flutter:
  assets:
    - assets/localization/

impaktfull_translations:
  app_uuid: "b6925bf4-f5c0-47cf-9724-792987c7a695"
  api_key: "05a73dc9-fdf3-48a9-984a-343c3c0df1f6"
  default_language: "nl"
  languages: ["en", "nl"]
  locale_assets_path: "assets/localization"
  assets_path: "assets/localization"
