name: impaktfull_translations
description: Dart tool to generate flutter translations code from the
  `impaktfull Dashboard - Translation App`
version: 0.0.4
homepage: https://github.com/impaktfull/flutter_impaktfull_translations
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  http: ^1.2.2
  locale_gen: ^12.1.3
  path: ^1.9.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.12
